# Pandas Practice Problems

In [47]:
# %load_ext pycodestyle_magic
# %flake8_on --ignore E266 --max_line_length 99

In [1]:
from urllib import request
from os import path
import pandas as pd
import numpy as np

In [6]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/"
fn = "forestfires.csv"
if not path.exists(fn):
    data = request.urlopen(url + fn).read()
    with open(fn, 'wb') as fhand:
        fhand.write(data)

ff = pd.read_csv("forestfires.csv")
print(ff.head())
print(ff.info())
print(ff.describe())

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    object
 3   day     517 non-null    object
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(3), object(2)
memory usage: 52.6+ KB
None
                X           Y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000

             temp          RH        wind        rain         area
count  517.000000  517.000000  517.000000  517.000000   517.000000
mean    18.889168   44.288201    4.017602    0.021663    12.847292
std      5.806625   16.317469    1.791653    0.295959    63.655818
min      2.200000   15.000000    0.400000    0.000000     0.000000
25%     15.500000   33.000000    2.700000    0.000000     0.000000
50%     19.300000   42.000000    4.000000    0.000000     0.520000
75%     22.800000   53.000000    4.900000    0.000000     6.570000
max     33.300000  100.000000    9.400000    6.400000  1090.840000

### Problem 1: Filtering and computing a mean
Write a function that returns the average rainfall on days with wind speed above 6 mph.

In [14]:
# ff.columns
# ff[ff['wind'] > 6]
# ff['rain'].mean()

def windy_rain():
    '''Returns average rainfall on days with wind speed above 6 mph'''
    windy_days = ff[ff['wind'] > 6] #filter for windy days
    return windy_days['rain'].mean() #average rainfall on windy days

In [15]:
assert abs(windy_rain() - 0.0412698) < 1e-6

### Problem 2: Filtering and computing a sum
Write a function that take a month as an argument and returns the total rainfall during the month.

In [23]:
# ff['month'].unique()
# ff['month'] == 'mar'
# ff[ff['month'] == 'mar'].shape
# ff['rain'].sum()

def monthly_rain(month):
    # filter data for the specified month
    month_data = ff[ff['month'] == month]

    #calculate total rainfall for the month
    return month_data['rain'].sum()

In [24]:
assert abs(monthly_rain("aug") - 10.8) < 1e-6
assert abs(monthly_rain("mar") - 0.2) < 1e-6

### Problem 3: Loading Pandas data frames
Download the white wine dataset from [https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv), and load it into a Pandas dataframe called `df`.

In [25]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/"
fn = "winequality-white.csv"
if not path.exists(fn):
    data = request.urlopen(url + fn).read()
    with open(fn, 'wb') as fhand:
        fhand.write(data)

# Load the data into a pandas DataFrame
# Note: This dataset uses semicolons as separators
df = pd.read_csv(fn, sep=';')
print(df.head())
print(df.info())
print(df.describe())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045
1            6.3              0.30         0.34             1.6      0.049
2            8.1              0.28         0.40             6.9      0.050
3            7.2              0.23         0.32             8.5      0.058
4            7.2              0.23         0.32             8.5      0.058

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45
1                 14.0                 132.0   0.9940  3.30       0.49
2                 30.0                  97.0   0.9951  3.26       0.44
3                 47.0                 186.0   0.9956  3.19       0.40
4                 47.0                 186.0   0.9956  3.19       0.40

   alcohol  quality
0      8.8        6
1      9.5        6
2     10.1        6
3      9.9        6
4      9.9        6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB
None
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000
mean        6.854788          0.278241     0.334192        6.391415
std         0.843868          0.100795     0.121020        5.072058
min         3.800000          0.080000     0.000000        0.600000
25%         6.300000          0.210000     0.270000        1.700000
50%         6.800000          0.260000     0.320000        5.200000
75%         7.300000          0.320000     0.390000        9.900000
max        14.200000          1.100000     1.660000       65.800000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000
mean      0.045772            35.308085            138.360657     0.994027
std       0.021848            17.007137             42.498065     0.002991
min       0.009000             2.000000              9.000000     0.987110
25%       0.036000            23.000000            108.000000     0.991723
50%       0.043000            34.000000            134.000000     0.993740
75%       0.050000            46.000000            167.000000     0.996100
max       0.346000           289.000000            440.000000     1.038980

                pH    sulphates      alcohol      quality
count  4898.000000  4898.000000  4898.000000  4898.000000
mean      3.188267     0.489847    10.514267     5.877909
std       0.151001     0.114126     1.230621     0.885639
min       2.720000     0.220000     8.000000     3.000000
25%       3.090000     0.410000     9.500000     5.000000
50%       3.180000     0.470000    10.400000     6.000000
75%       3.280000     0.550000    11.400000     6.000000
max       3.820000     1.080000    14.200000     9.000000

In [26]:
assert abs(df["citric acid"].mean() - 0.3341915) < 1e-8

### Problem 4: pipe
Write a function that takes a user-defined function as an argument.
It uses `pipe` to apply the function to each wine pH, and returns the mean of the values returned by the user-defined function.

In [29]:
# df['pH']

def mean_ph(user_fun):
    '''Takes user-defined function; uses pipe to apply function to each wine pH and returns the mean'''
    return df['pH'].pipe(user_fun).mean()

In [30]:
assert abs(mean_ph(lambda x: x**2) - (df.pH ** 2).mean()) < 1e-8

### Additional Exercises (pandas)

### Pandas Series Basics

In [57]:
import pandas as pd 
import numpy as np 

# Series Basics 
print("------ Series Basics ------\n")
numbers = np.random.randn(5)
s = pd.Series(numbers)
print(s)

# Series Creation 
print("\n------ Series Creation ------\n")
idx = ['a', 'b', 'c', 'd', 'e']
s2 = pd.Series(numbers, index=idx)
print(s2)

print("\n------Series Creation (from dictionary) ------\n")
d = {'dog':3.1415, 'cat':42, 'bird':0, 'goat':1.618, 'cthulu':np.nan}
s = pd.Series(d); print(s)

print("\n------ Series Indexing ------\n")
inds = ['dog', 'cat', 'bird', 'goat', 'chutlu'] # chutlu not in d; NaN result
s = pd.Series(d, index=inds); print(s)

------ Series Basics ------

0   -1.027202
1    0.667059
2   -0.172998
3   -1.314530
4   -0.222078
dtype: float64

------ Series Creation ------

a   -1.027202
b    0.667059
c   -0.172998
d   -1.314530
e   -0.222078
dtype: float64

------Series Creation (from dictionary) ------

dog        3.1415
cat       42.0000
bird       0.0000
goat       1.6180
cthulu        NaN
dtype: float64

------ Series Indexing ------

dog        3.1415
cat       42.0000
bird       0.0000
goat       1.6180
chutlu        NaN
dtype: float64

In [58]:
print("\n------ Series properties ------\n")
numbers = np.array([2, 50.0, 113.0, 4, 9,])
s = pd.Series(numbers, name = 'sale'); print(s)
print("\n Common attributes:")
print(f"Name: {s.name}")
print(f"dtype: {s.dtype}")
print(f"Index: {s.index}")
print(f"Size: {s.size}")
print(f"Shape: {s.shape}")
print(f"Values: {s.values}")

------ Series properties ------

0      2.0
1     50.0
2    113.0
3      4.0
4      9.0
Name: sale, dtype: float64

 Common attributes:
Name: sale
dtype: float64
Index: RangeIndex(start=0, stop=5, step=1)
Size: 5
Shape: (5,)
Values: [  2.  50. 113.   4.   9.]

### Pandas Series Operations

In [59]:
print("\n------ Indexing ------\n")
s = pd.Series([2, 3, 5, 7, 11])
print(s)
print(s[0]) # first element
print(s[1:3]) # slice elements 1 and 2
# s[-1] # doesn't work

print("\n ----- Non-Unique Indices -----\n")
s = pd.Series([1, 2, 3, 2, 1], index=['a','a', 'a', 'a', 'a'])
print(s['a']) #indices need not be unique

------ Indexing ------

0     2
1     3
2     5
3     7
4    11
dtype: int64
2
1    3
2    5
dtype: int64

 ----- Non-Unique Indices -----

a    1
a    2
a    3
a    2
a    1
dtype: int64

In [60]:
print("\n------ Slicing and func like NumPy ------\n")
d = {'dog':3.1415, 'cat':42, 'bird':0, 'goat':1.618, 'cthulu':np.nan}
s = pd.Series(d)
print(s)
print(s[s > 0]) #boolean indexing; indices included 
print(s**2) #element-wise squaring; supported NumPy ufunc

print("\n------ Modifying Series like a dictionary ------\n")
print(s['goat'])
s['cthulu'] = -1; print(s)
# s['penguin'] #KeyError: 'penguin' not found in Series
# s['cthulu'] = (1, 1) # ValueError; cannot assign tuple 
# s['dog'] = [1,1] # ValueError; cannot assign list

------ Slicing and func like NumPy ------

dog        3.1415
cat       42.0000
bird       0.0000
goat       1.6180
cthulu        NaN
dtype: float64
dog      3.1415
cat     42.0000
goat     1.6180
dtype: float64
dog          9.869022
cat       1764.000000
bird         0.000000
goat         2.617924
cthulu            NaN
dtype: float64

------ Modifying Series like a dictionary ------

1.618
dog        3.1415
cat       42.0000
bird       0.0000
goat       1.6180
cthulu    -1.0000
dtype: float64

In [61]:
print("\n------ Universal functions on Series ------\n")
s['cthulu'] = 'abcde'
print(s)
print(s + 2*s)
d = {'dog': 2, 'cat': 1.23456}
t = pd.Series(d); print(t)
s + t

print("\n------ Methods ------\n")
s.name = 'aminals'; print(s)
s.rename('animals', inplace=True); print(s)

------ Universal functions on Series ------

dog       3.1415
cat         42.0
bird         0.0
goat       1.618
cthulu     abcde
dtype: object
dog                9.4245
cat                 126.0
bird                  0.0
goat                4.854
cthulu    abcdeabcdeabcde
dtype: object
dog    2.00000
cat    1.23456
dtype: float64

------ Methods ------

dog       3.1415
cat         42.0
bird         0.0
goat       1.618
cthulu     abcde
Name: aminals, dtype: object
dog       3.1415
cat         42.0
bird         0.0
goat       1.618
cthulu     abcde
Name: animals, dtype: object

C:\Users\Bryant Willoughby\AppData\Local\Temp\ipykernel_41216\58545515.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'abcde' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  s['cthulu'] = 'abcde'

In [62]:
print("\n------ Mapping and linking Series values ------\n")
s = pd.Series(['dog', 'goat', 'skunk']); print(s)
s.map(lambda s: len(s)) #takes function and applies to each element

s = pd.Series(['fruit', 'animal', 'animal', 'fruit', 'fruit'], 
              index = ['apple', 'cat', 'goat', 'banana', 'kiwi'])
print(s)

t = pd.Series({'fruit': 0, 'animal': 1})
s.map(t)

------ Mapping and linking Series values ------

0      dog
1     goat
2    skunk
dtype: object
apple      fruit
cat       animal
goat      animal
banana     fruit
kiwi       fruit
dtype: object

apple     0
cat       1
goat      1
banana    0
kiwi      0
dtype: int64

### Pandas Data Frames

In [63]:
print("------ Pandas Data Frames Creation ------")
d = {'A': pd.Series([1, 2, 3], index=['cat', 'dog', 'bird']), 
     'B':{'cat': 3.14, 'dog': 2.71, 'bird': 1.41, 'goat': 1.73}}
df = pd.DataFrame(d)
print(df)

d = {'Undergrad': pd.Series(['Umich', 'Stanford', 'Princeton', 'Columbia'], 
                            index = ['Ford', 'Hoover', 'Wilson', 'Obama']), 
    'PhD': {'Wilson': 'Johns Hopkins'}, 
    'JD': {'Ford': 'Yale', 'Obama': 'Harvard'}, 
    'Terms': pd.Series([1,1,2,2], index = ['Hoover', 'Ford', 'Wilson', 'Obama'])}
presidents = pd.DataFrame(d); print("\n",presidents)

print("\n----- row/column as attributes -----")
print(presidents.columns) # Pandas Index object
print(presidents.index)

print("\n----- Accessing/adding columns -----")
print(presidents['PhD']) #access column as dictionary
presidents['Years'] = 4*presidents['Terms'] #add new column
presidents['Nobels'] = [0, 0, 1, 1] #add new column
presidents['Field Medals'] = 0 #scalars broadcast across the rows
print(presidents)

print("\n----- Deleting columns -----")
del presidents['Years']
print(presidents)
fields = presidents.pop('Field Medals') #removes and returns column
print(fields)

------ Pandas Data Frames Creation ------
        A     B
bird  3.0  1.41
cat   1.0  3.14
dog   2.0  2.71
goat  NaN  1.73

         Undergrad            PhD       JD  Terms
Ford        Umich            NaN     Yale      1
Hoover   Stanford            NaN      NaN      1
Obama    Columbia            NaN  Harvard      2
Wilson  Princeton  Johns Hopkins      NaN      2

----- row/column as attributes -----
Index(['Undergrad', 'PhD', 'JD', 'Terms'], dtype='object')
Index(['Ford', 'Hoover', 'Obama', 'Wilson'], dtype='object')

----- Accessing/adding columns -----
Ford                NaN
Hoover              NaN
Obama               NaN
Wilson    Johns Hopkins
Name: PhD, dtype: object
        Undergrad            PhD       JD  Terms  Years  Nobels  Field Medals
Ford        Umich            NaN     Yale      1      4       0             0
Hoover   Stanford            NaN      NaN      1      4       0             0
Obama    Columbia            NaN  Harvard      2      8       1             0
Wilson  Princeton  Johns Hopkins      NaN      2      8       1             0

----- Deleting columns -----
        Undergrad            PhD       JD  Terms  Nobels  Field Medals
Ford        Umich            NaN     Yale      1       0             0
Hoover   Stanford            NaN      NaN      1       0             0
Obama    Columbia            NaN  Harvard      2       1             0
Wilson  Princeton  Johns Hopkins      NaN      2       1             0
Ford      0
Hoover    0
Obama     0
Wilson    0
Name: Field Medals, dtype: int64

In [64]:
print("\n----- Indexing & Selection -----")
print(presidents.loc['Obama']) #selects row by label 
print(presidents.iloc[2]) #selects row by integer position
print(presidents['JD']) #select column by name 
print(presidents[1:3])
print(presidents[presidents['Terms'] < 2])

----- Indexing & Selection -----
Undergrad    Columbia
PhD               NaN
JD            Harvard
Terms               2
Nobels              1
Name: Obama, dtype: object
Undergrad    Columbia
PhD               NaN
JD            Harvard
Terms               2
Nobels              1
Name: Obama, dtype: object
Ford         Yale
Hoover        NaN
Obama     Harvard
Wilson        NaN
Name: JD, dtype: object
       Undergrad  PhD       JD  Terms  Nobels
Hoover  Stanford  NaN      NaN      1       0
Obama   Columbia  NaN  Harvard      2       1
       Undergrad  PhD    JD  Terms  Nobels
Ford       Umich  NaN  Yale      1       0
Hoover  Stanford  NaN   NaN      1       0

In [65]:
print("\n------ Arithmetic -------")
df1 = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(5, 3), columns = ['A', 'B', 'C'])
print(df1 + df2) #fills non-alignable entries with NaN

df = pd.DataFrame(np.random.randn(4, 2), columns = ['A', 'B'])
print(df)
print(df - df.iloc[0]) #row-wise subtraction (broadcasting)
print(10*df + 1)
print(df > 0)

------ Arithmetic -------
          A         B         C   D
0 -1.481082 -3.468940  1.005588 NaN
1 -0.310566  1.991625  0.812539 NaN
2  0.472299 -0.175808  3.013166 NaN
3  0.650209  1.535228  0.551978 NaN
4  0.445085 -0.499523 -0.721345 NaN
5       NaN       NaN       NaN NaN
6       NaN       NaN       NaN NaN
7       NaN       NaN       NaN NaN
          A         B
0  0.204805 -1.153413
1 -0.097870  0.732229
2 -0.020744  0.433837
3  0.652779  0.078722
          A         B
0  0.000000  0.000000
1 -0.302674  1.885642
2 -0.225548  1.587250
3  0.447974  1.232135
          A          B
0  3.048045 -10.534126
1  0.021303   8.322294
2  0.792563   5.338374
3  7.527786   1.787222
       A      B
0   True  False
1  False   True
2  False   True
3   True   True

In [66]:
print("\n----- Arithmetic with DataFrames -----")
print(df)
print((df > 0).any())
print((df > 0).all())
# df or df # unsupported as also seen in NumPy
print(df.values) #get underlying NumPy array
print(df.T) #transpose of DataFrame
print(df.T * df.T) #entrywise multiplication 
print(df.T.dot(df)) #matrix multiplication

----- Arithmetic with DataFrames -----
          A         B
0  0.204805 -1.153413
1 -0.097870  0.732229
2 -0.020744  0.433837
3  0.652779  0.078722
A    True
B    True
dtype: bool
A    False
B    False
dtype: bool
[[ 0.20480453 -1.15341261]
 [-0.09786973  0.73222936]
 [-0.0207437   0.43383739]
 [ 0.65277865  0.07872216]]
          0         1         2         3
A  0.204805 -0.097870 -0.020744  0.652779
B -1.153413  0.732229  0.433837  0.078722
          0         1         2         3
A  0.041945  0.009578  0.000430  0.426120
B  1.330361  0.536160  0.188215  0.006197
          A         B
A  0.478074 -0.265498
B -0.265498  2.060933

In [67]:
print("\n------ Removing NaNs -------")
df['C'] = [1, np.nan, 3, np.nan]
df['D'] = [np.nan, np.nan, np.nan, np.nan]
print(df)
print(df.dropna(axis=1, how='any')) #drops columns with any NaNs
print(df.dropna(axis=1, how='all')) #drops columns with all NaNs

------ Removing NaNs -------
          A         B    C   D
0  0.204805 -1.153413  1.0 NaN
1 -0.097870  0.732229  NaN NaN
2 -0.020744  0.433837  3.0 NaN
3  0.652779  0.078722  NaN NaN
          A         B
0  0.204805 -1.153413
1 -0.097870  0.732229
2 -0.020744  0.433837
3  0.652779  0.078722
          A         B    C
0  0.204805 -1.153413  1.0
1 -0.097870  0.732229  NaN
2 -0.020744  0.433837  3.0
3  0.652779  0.078722  NaN

In [68]:
# # Summarizing DataFrames 
# baseball = pd.read_csv('baseball.csv')
# baseball.info()
# baseball.head()
# baseball.describe()

In [69]:
print("\n------ Comparing DataFrames -------")
print(df)
df1 = 2*df
df2 = df + df
(df1 == df2).all()
print(np.nan == np.nan) #False; NaN not equal to NaN by definition
print(df1.equals(df2)) #True

print("\n----- Statistical Operations on DataFrames -----")
print(df)
print(np.nanmean(np.array(df.iloc[1]))) #ignores NaN; possible but tedious w/ NumPy
print(df.mean(axis = 0)) #column-wise mean; ignores NaN by default
print(df.mean(axis = 1)) #row-wise mean; ignores NaN by default

------ Comparing DataFrames -------
          A         B    C   D
0  0.204805 -1.153413  1.0 NaN
1 -0.097870  0.732229  NaN NaN
2 -0.020744  0.433837  3.0 NaN
3  0.652779  0.078722  NaN NaN
False
True

----- Statistical Operations on DataFrames -----
          A         B    C   D
0  0.204805 -1.153413  1.0 NaN
1 -0.097870  0.732229  NaN NaN
2 -0.020744  0.433837  3.0 NaN
3  0.652779  0.078722  NaN NaN
0.31717981436682724
A    0.184742
B    0.022844
C    2.000000
D         NaN
dtype: float64
0    0.017131
1    0.317180
2    1.137698
3    0.365750
dtype: float64

In [70]:
print("\n----- Row and Column-wise function: apply() -----")
print(df.apply(np.mean)) #column-wise mean; default axis=0
print(df.apply(np.mean, axis=1)) #row-wise mean

def quadratic(x, a, b, c=1): 
    return a*x**2 + b*x + c
df.apply(quadratic, args=(2, 3), c=3) #applies quadratic to each column

----- Row and Column-wise function: apply() -----
A    0.184742
B    0.022844
C    2.000000
D         NaN
dtype: float64
0    0.017131
1    0.317180
2    1.137698
3    0.365750
dtype: float64

          A         B     C   D
0  3.698303  2.200483   8.0 NaN
1  2.725548  6.269008   NaN NaN
2  2.938630  4.677942  30.0 NaN
3  5.810576  3.248561   NaN NaN

In [72]:
print("\n----- Element-wise function application ----")
d = {'A': pd.Series(['cat', 'dog', 'bird']), 
     'B': pd.Series(['unicorn', 'dragon', 'griffin'])}
df = pd.DataFrame(d); print(df)
df.applymap(lambda s:s.upper())

----- Element-wise function application ----
      A        B
0   cat  unicorn
1   dog   dragon
2  bird  griffin

C:\Users\Bryant Willoughby\AppData\Local\Temp\ipykernel_41216\489921853.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda s:s.upper())

      A        B
0   CAT  UNICORN
1   DOG   DRAGON
2  BIRD  GRIFFIN